### Librerias

In [1]:
#LIBRERIAS NECESARIAS
import pandas as pd
import numpy as np

In [ ]:
# DICCIONARIO
# Homicidios en accidentes de tránsito = 1 
# Hurtos autos = 2
# Hurtos a comercio = 3
# Hurtos a residencias = 4 
# Homicidios = 5 
# Hurtos personas = 6
# Lesiones transito = 7

# for i,e in zip(["hom_acc", "hurt_auto", "hurt_comercio", "hurt_residencia", "homicidios", "hurt_personas", "lesi_acc" ], [1,2,3,4,5,6,7]):
#     total["tipo"]=total["tipo"].replace(e,i)

### Delitos

#### 1. Homicidios en accidentes de transito

In [4]:
#1. HOMICIDIOS EN ACCIDENTES DE TRANSITO
df=pd.read_excel("homicidios-accidentes-transito-2012.xls")
df=df[(df["Municipio"]=="VALLEDUPAR (CT)")]

#APPEND CON TODOS LOS AÑOS
for i in range(13,20):
    A=pd.read_excel(f"homicidios-accidentes-transito-20{i}.xls")
    A=A[(A["Municipio"]=="VALLEDUPAR (CT)")]
    df=pd.concat([df, A])  

#CONVERTIR LAS COLUMNAS A MINUSCULAS
c2=[]
for i in df.columns:
    c2.append(i.lower())
df.columns=c2
df.columns
df.rename(columns={"día": "dia"}, inplace=True)

#CONSERVAR SOLO LAS COLUMNAS DE INTERÉS
df=df[['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima','cantidad']]

#CREAR UNA COLUMNA PARA EL TIPO Y GUARDAR EL ARCHIVO CSV
df["tipo"]="HT"
df.to_csv("1HT.csv", encoding="latin-1", index=False)

In [11]:
df.head()

,fecha,departamento,municipio,dia,hora,barrio,zona,clase de sitio,arma empleada,móvil agresor,móvil victima,cantidad,clase,marca,linea,color,modelo,tipo
6,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,03:00:00,BALNEARIO HURTADO,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,CONDUCTOR MOTOCICLETA,CONDUCTOR VEHICULO,1,CAMPERO,CHEVROLET,VITARA,BLANCO,2009,HA
7,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,01:00:00,SAN FERNANDO,URBANA,VIAS PUBLICAS,LLAVE MAESTRA,A PIE,A PIE,1,AUTOMOVIL,MAZDA,626 NMO,PLATA,2003,HA
950,2012-02-05,CESAR,VALLEDUPAR (CT),Domingo,01:30:00,CAÑAGUATE,URBANA,VIAS PUBLICAS,LLAVE MAESTRA,A PIE,A PIE,1,AUTOMOVIL,MAZDA,6L3NA4,VERDE,2004,HA
951,2012-02-05,CESAR,VALLEDUPAR (CT),Domingo,01:30:00,CAÑAGUATE,URBANA,VIAS PUBLICAS,LLAVE MAESTRA,A PIE,A PIE,1,AUTOMOVIL,CHEVROLET,AVEO L,BEIGE,2007,HA
1267,2012-02-15,CESAR,VALLEDUPAR (CT),Miércoles,00:00:00,-,RURAL,FINCAS Y SIMILARES,ARMA DE FUEGO,A PIE,A PIE,1,CAMIONETA,TOYOTA,HILUX,BLANCO,2009,HA

#### 2. Hurto de automotores

In [8]:
#2. HURTO DE AUTOMOTORES
 
df=pd.read_excel("hurto-de-automotores-2012.xls")
df=df[(df["Municipio"]=="VALLEDUPAR (CT)")]

for i in range(13,20):
    A=pd.read_excel(f"hurto-de-automotores-20{i}.xls")
    A=A[(A["Municipio"]=="VALLEDUPAR (CT)")]
    df=pd.concat([df, A])  

c2=[]
for i in df.columns:
    c2.append(i.lower())
df.columns=c2
df.columns
df.rename(columns={"día": "dia"}, inplace=True)

df=df[['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima','cantidad','clase', 'marca', 'linea', 'color','modelo']]

df["tipo"]="HA"
df.to_csv("2HA.csv", index=False)

In [10]:
df.head()

,fecha,departamento,municipio,dia,hora,barrio,zona,clase de sitio,arma empleada,móvil agresor,móvil victima,cantidad,clase,marca,linea,color,modelo,tipo
6,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,03:00:00,BALNEARIO HURTADO,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,CONDUCTOR MOTOCICLETA,CONDUCTOR VEHICULO,1,CAMPERO,CHEVROLET,VITARA,BLANCO,2009,HA
7,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,01:00:00,SAN FERNANDO,URBANA,VIAS PUBLICAS,LLAVE MAESTRA,A PIE,A PIE,1,AUTOMOVIL,MAZDA,626 NMO,PLATA,2003,HA
950,2012-02-05,CESAR,VALLEDUPAR (CT),Domingo,01:30:00,CAÑAGUATE,URBANA,VIAS PUBLICAS,LLAVE MAESTRA,A PIE,A PIE,1,AUTOMOVIL,MAZDA,6L3NA4,VERDE,2004,HA
951,2012-02-05,CESAR,VALLEDUPAR (CT),Domingo,01:30:00,CAÑAGUATE,URBANA,VIAS PUBLICAS,LLAVE MAESTRA,A PIE,A PIE,1,AUTOMOVIL,CHEVROLET,AVEO L,BEIGE,2007,HA
1267,2012-02-15,CESAR,VALLEDUPAR (CT),Miércoles,00:00:00,-,RURAL,FINCAS Y SIMILARES,ARMA DE FUEGO,A PIE,A PIE,1,CAMIONETA,TOYOTA,HILUX,BLANCO,2009,HA

#### 3. Hurto a comercios

In [13]:
#3. HURTO COMERCIO
 
df=pd.read_excel("hurto-comercio-2012.xlsx")
df=df[(df["Municipio"]=="VALLEDUPAR (CT)")]

for i in range(13,20):
    A=pd.read_excel(f"hurto-comercio-20{i}.xlsx")
    A=A[(A["Municipio"]=="VALLEDUPAR (CT)")]
    df=pd.concat([df, A])  

c2=[]
for i in df.columns:
    c2.append(i.lower())
df.columns=c2
df.columns
df.rename(columns={"día": "dia"}, inplace=True)

df=df[['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima','cantidad']]

df["tipo"]="HC"
df.to_csv("3HC.csv", encoding="latin-1", index=False)

In [14]:
df.head()

,fecha,departamento,municipio,dia,hora,barrio,zona,clase de sitio,arma empleada,móvil agresor,móvil victima,cantidad,tipo
10,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,21:20:00,LAS FLORES,URBANA,VIAS PUBLICAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HC
73,2012-01-02,CESAR,VALLEDUPAR (CT),Lunes,15:00:00,7 DE AGOSTO,URBANA,TALLERES,ARMA DE FUEGO,A PIE,A PIE,1,HC
255,2012-01-05,CESAR,VALLEDUPAR (CT),Jueves,02:00:00,GAITAN,URBANA,OFICINAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HC
256,2012-01-05,CESAR,VALLEDUPAR (CT),Jueves,04:20:00,CENTRO,URBANA,VIAS PUBLICAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HC
257,2012-01-05,CESAR,VALLEDUPAR (CT),Jueves,09:00:00,LA GRANJA,URBANA,EMPRESA,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HC

#### 4. Hurto a residencias

In [17]:
#4. HURTO RESIDENCIAS
 
df=pd.read_excel("hurto-residencias-2012.xlsx")
df=df[(df["Municipio"]=="VALLEDUPAR (CT)")]

for i in range(13,20):
    A=pd.read_excel(f"hurto-residencias-20{i}.xlsx")
    A=A[(A["Municipio"]=="VALLEDUPAR (CT)")]
    df=pd.concat([df, A])  

c2=[]
for i in df.columns:
    c2.append(i.lower())
df.columns=c2
df.columns
df.rename(columns={"día": "dia"}, inplace=True)

df=df[['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima','cantidad']]

df["tipo"]="HR"
df.to_csv("4HR.csv", encoding="latin-1", index=False)

In [18]:
df.head()

,fecha,departamento,municipio,dia,hora,barrio,zona,clase de sitio,arma empleada,móvil agresor,móvil victima,cantidad,tipo
35,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,20:00:00,CONJ PORTAL DEL ROSARIO,URBANA,CASAS DE HABITACION,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HR
36,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,09:00:00,PANAMA,URBANA,CASAS DE HABITACION,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HR
37,2012-01-01,CESAR,VALLEDUPAR (CT),Domingo,00:30:00,ALTAGRACIA,URBANA,CASAS DE HABITACION,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HR
126,2012-01-02,CESAR,VALLEDUPAR (CT),Lunes,19:00:00,URB. CLUB HOUSE,URBANA,CASAS DE HABITACION,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HR
127,2012-01-02,CESAR,VALLEDUPAR (CT),Lunes,02:00:00,-,URBANA,INSTALACIONES DEL EJERCITO,CONTUNDENTES,A PIE,-,1,HR

#### 5.Homicidios

In [19]:
#5. HOMCIDIOS
df=pd.read_excel("homicidios-2012.xls")
df=df[(df["Municipio"]=="VALLEDUPAR (CT)")]

for i in range(13,20):
    A=pd.read_excel(f"homicidios-20{i}.xls")
    A=A[(A["Municipio"]=="VALLEDUPAR (CT)")]
    df=pd.concat([df, A]) 

c2=[]
for i in df.columns:
    c2.append(i.lower())
df.columns=c2
df.columns

df.rename(columns={"día": "dia"}, inplace=True)

df=df[['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima','cantidad']]

df["tipo"]="H"
df.to_csv("5H.csv", encoding="latin-1", index=False)

In [20]:
df.head()

,fecha,departamento,municipio,dia,hora,barrio,zona,clase de sitio,arma empleada,móvil agresor,móvil victima,cantidad,tipo
181,2012-01-04,CESAR,VALLEDUPAR (CT),Miércoles,19:50:00,NUEVO MILENIO,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,1,H
223,2012-01-05,CESAR,VALLEDUPAR (CT),Jueves,15:15:00,CIUDAD TAYRONA I,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,1,H
340,2012-01-08,CESAR,VALLEDUPAR (CT),Domingo,01:15:00,LOS CACIQUES,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,1,H
416,2012-01-10,CESAR,VALLEDUPAR (CT),Martes,14:55:00,CANDELARIA SUR,URBANA,VIAS PUBLICAS,CONTUNDENTES,A PIE,A PIE,1,H
417,2012-01-10,CESAR,VALLEDUPAR (CT),Martes,15:00:00,LA NEVADA,URBANA,VIAS PUBLICAS,ARMA BLANCA,A PIE,A PIE,1,H

#### 6.Hurto a personas

In [22]:
#6. HURTO A PERSONAS 
df=pd.read_excel("hurto-personas-2012.xlsx")
df=df[(df["Municipio"]=="VALLEDUPAR (CT)")]

for i in range(13,20):
    A=pd.read_excel(f"hurto-personas-20{i}.xlsx")
    A=A[(A["Municipio"]=="VALLEDUPAR (CT)")]
    df=pd.concat([df, A])  

c2=[]
for i in df.columns:
    c2.append(i.lower())
df.columns=c2
df.columns
df.rename(columns={"día": "dia"}, inplace=True)

df=df[['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima','cantidad']]

df["tipo"]="HP"
df.to_csv("6HP.csv", encoding="latin-1", index=False)

In [24]:
df.head()

,fecha,departamento,municipio,dia,hora,barrio,zona,clase de sitio,arma empleada,móvil agresor,móvil victima,cantidad,tipo
40039,2012-01-02,CESAR,VALLEDUPAR (CT),Lunes,00:00:00,CASIMIRO MASTRE,URBANA,PARQUEADERO,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HP
40040,2012-01-03,CESAR,VALLEDUPAR (CT),Martes,09:00:00,CENTRO,URBANA,VIAS PUBLICAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HP
40041,2012-01-03,CESAR,VALLEDUPAR (CT),Martes,17:00:00,CENTRO,URBANA,VIAS PUBLICAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HP
40042,2012-01-04,CESAR,VALLEDUPAR (CT),Miércoles,10:20:00,GAITAN,URBANA,VIAS PUBLICAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,1,HP
40043,2012-01-05,CESAR,VALLEDUPAR (CT),Jueves,15:30:00,VILLA MONICA,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,CONDUCTOR MOTOCICLETA,PASAJERO MOTOCICLETA,1,HP

#### 7.Lesiones en accidentes de transito

In [26]:
#7. LESIONES EN ACCIDENTES DE TRANSITO 
df=pd.read_excel("lesiones_en_accidente_de_transito_2012_0.xlsx")
df=df[(df["MUNICIPIO"]=="VALLEDUPAR (CT)")]

for i in range(13,20):
    A=pd.read_excel(f"lesiones_en_accidente_de_transito_20{i}_0.xlsx")
    A=A[(A["MUNICIPIO"]=="VALLEDUPAR (CT)")]
    df=pd.concat([df, A])  

#CREAR EL DÍA Y REEMPLAZARLO POR EL NOMBRE EL ESPAÑOL
df["dia"]=df["FECHA HECHO"].map(lambda x: x.strftime("%A"))
for i,e in zip(['Friday', 'Saturday', 'Monday', 'Tuesday', 'Thursday', 'Sunday','Wednesday'], ["Viernes", "Sábado", "Lunes", "Martes", "Jueves", "Domingo", "Miércoles"]):
    df["dia"]=df["dia"].replace(i, e)

#CREAR COLUMNAS DE INTERÉS PARA PODER HACER EL APPEND CON LOS DEMÁS ARCHIVOS
df["fecha"]=df["FECHA HECHO"]
df["hora"] = np.nan
df["barrio"] = np.nan
df["zona"] = np.nan
df["clase de sitio"] = np.nan
df["arma empleada"] = np.nan
df["móvil agresor"] = df["ARMAS MEDIOS"]
df["cantidad"] = df["CANTIDAD"]
df["móvil victima"] = np.nan
df["municipio"] = df["MUNICIPIO"]
df["departamento"] = df["DEPARTAMENTO"]

#CONSERVAR SOLO COLUMNAS DE INTERÉS
df=df[['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima','cantidad']]


#CONVERTIR COLUMNAS A MINUSCULAS
c2=[]
for i in df.columns:
    c2.append(i.lower())
df.columns=c2
df.columns
df.rename(columns={"día": "dia"}, inplace=True)


#GUARDAR
df["tipo"]="LT"
df.to_csv("7LT.csv", encoding="latin-1", index=False)

### Pegue de las bases

In [5]:
bases = ["1HT.csv", "2HA.csv", "3HC.csv", "4HR.csv", "5H.csv", "6HP.csv", "7LT.csv"]

In [6]:
df = pd.DataFrame()

for base in bases:
    lectura = pd.read_csv(base, encoding="latin-1")
    lectura = lectura.rename(columns = {'mÃ³vil agresor': 'móvil agresor', 'mÃ³vil victima': 'móvil victima'})
    print(lectura.columns)
    df = pd.concat([df, lectura])

df=df.replace("-", np.nan)

Index(['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima',
       'cantidad', 'tipo'],
      dtype='object')
Index(['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima',
       'cantidad', 'clase', 'marca', 'linea', 'color', 'modelo', 'tipo'],
      dtype='object')
Index(['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima',
       'cantidad', 'tipo'],
      dtype='object')
Index(['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima',
       'cantidad', 'tipo'],
      dtype='object')
Index(['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima',
       'cantidad', 'tipo'],
      dtype='object')
Index(['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima',
       'cantidad', 'tipo'],
      dtype='object')
Index(['fecha', 'departamento', 'municipio', 'dia', 'hora', 'barrio', 'zona',
       'clase de sitio', 'arma empleada', 'móvil agresor', 'móvil victima',
       'cantidad', 'tipo'],
      dtype='object')

In [7]:
df.to_csv('0_delitos_totales.csv', encoding="latin-1", index=False)

### Ordenamiento base econometría

Corrección de barrio

In [28]:
barrios = df[["barrio"]].drop_duplicates().sort_values(by = ["barrio"])

A = ["1Âº DE MAYO",
"BALNERIO HURTADO",
"CAÃAGUATE",
"CIUDADELA 450 AÃOS"
"DIVINO NIÃO"]

B = ["1º DE MAYO",
"BALNEARIO HURTADO",
"CAÑAGUATE",
"CIUDADELA 450 AÑOS",
"DIVINO NIÑO"]

for a,b in zip(A,B):
    df["barrio"] = df["barrio"].replace(a,b)

barrios = df[["barrio"]].drop_duplicates().sort_values(by = ["barrio"])

Filtro de armas

Filtro de moviles

Filtro de delito

Panel

In [77]:
panel = df.groupby(["fecha", "barrio", "zona"])[["cantidad"]].sum().reset_index()
panel.fecha = pd.to_datetime(panel.fecha)

Balancear panel

In [174]:
from datetime import date, timedelta
from itertools import product

In [175]:
date_range = pd.date_range(start=panel.fecha.iloc[0], 
                           end=panel.fecha.iloc[-1], 
                           freq='D')

barrios = panel.barrio.unique()

combinations = product(date_range, barrios)

data = list(combinations)
data = pd.DataFrame(data, columns=['fecha', 'barrio'])

In [176]:
data = pd.merge(data, panel[["barrio", "zona"]].drop_duplicates("barrio"), "left", ['barrio'])
data = pd.merge(data, panel, "left", ['fecha', 'barrio', 'zona'])
data.cantidad = data.cantidad.fillna(0)

Dia de la semana

In [177]:
from datetime import datetime
data['dia'] = data['fecha'].apply(lambda x: x.strftime('%A'))

Crear controles de dias: dias antes y después del tratamiento, festivos

In [178]:
from datetime import datetime

def dias_entre_fechas(fecha1, fecha2):
    # Convertir las fechas en objetos datetime si son cadenas
    if isinstance(fecha1, str):
        fecha1 = datetime.strptime(fecha1, "%Y-%m-%d")
    if isinstance(fecha2, str):
        fecha2 = datetime.strptime(fecha2, "%Y-%m-%d")
    
    # Calcular la diferencia entre las dos fechas
    diferencia = fecha2 - fecha1

    # Devolver la cantidad de días como un número entero
    return diferencia.days

In [179]:
rangot = data[["fecha"]].drop_duplicates().reset_index(drop = True)

rangot["fecha_centrada"] = rangot["fecha"].apply(
    lambda x: 
    dias_entre_fechas(pd.to_datetime("2014-07-26"), x))

data = pd.merge(data, rangot, "left", "fecha")

Crear variables finales

In [187]:
data["T"] = data.dia.apply(lambda x: 1 if x == "Saturday" else 0)
data["P"] = data.fecha_centrada.apply(lambda x: 1 if x>=0 else 0)
data["TP"] = data["T"]*data["P"]

Tendencias paralelas

In [182]:
import matplotlib.pyplot as plt
data["mes"] = data["fecha"].apply(lambda x: x.replace(day=1))
distribucion = data.groupby(["T", "mes"])["cantidad"].mean().reset_index()
control = distribucion[distribucion["T"]==0]
tratados = distribucion[distribucion["T"]==1]
datet = data[data.fecha_centrada==0]["fecha"].iloc[0]
#1
fig, ax = plt.subplots(figsize=(20,6))
plt.plot(control["mes"], control["cantidad"], color="black")
plt.plot(tratados["mes"], tratados["cantidad"], color="gray")
# plt.text(0.98, 0.1, 'resto', horizontalalignment='left',verticalalignment='center', transform=ax.transAxes, color="black")
# plt.text(0.98, 0.05, 'sábados', horizontalalignment='left',verticalalignment='center', transform=ax.transAxes, color="gray")
ax.set_xticks(ax.get_xticks()[1::])
ax.axvline(datet, color='r', linestyle='--', lw=2)
# plt.xlabel("semanas")
# plt.ylabel("delitos")
# plt.title("sábados vs resto de días")

# #2
# fig, ax = plt.subplots(figsize=(20,6))
# plt.plot(resto_nm["año-semana"], resto_nm["cantidad"], color="black")
# plt.plot(sabado["año-semana"], sabado["cantidad"], color="gray")
# plt.text(0.98, 0.1, 'resto', horizontalalignment='left',verticalalignment='center', transform=ax.transAxes, color="black")
# plt.text(0.98, 0.05, 'sábados', horizontalalignment='left',verticalalignment='center', transform=ax.transAxes, color="gray")
# ax.set_xticks(ax.get_xticks()[::14])
# ax.axvline('2014-29', color='r', linestyle='--', lw=2)
# plt.xlabel("semanas")
# plt.ylabel("delitos")